### ISSUE TITLE
Name not being saved to .brackets.json

### ISSUE THREAD

**Issue by mihawk90** [petetnt/brackets-name-a-project#4]
As said in adobe/brackets#10538 my installation doesn't seem to save the project name in the (projects) .brackets.json file. The project name as well as the color are saved perfectly fine though, after multiple restarts the name wasn't forgotten once.

Could there be an issue with the project sitting on a network share? I've had multiple issues with network shares already so it wouldn't suprise me (I cannot stay away from network share though even if I wanted).

I don't know if it was badly formulated, but I did mean the project related json file, not the overall settings json file in %appdata%

**Comment by petetnt** [comment]
Oh right, I had forgotten about `.brackets.json` files.

There are two levels of preferences as stated [here](https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#scope-of-preferences):

> Scope of preferences
> - User-global preferences - your default settings. To edit, choose Debug > Open Preferences File.
> - Project-level preferences - override any number of preferences on a project-specific basis. Create a > \* .brackets.json file in the root of your project.

By default this extension does save the values to the user global preferences (the brackets.json in %APPDATA%) by default, but if the `key` is already in `.brackets.json`, it will save it there.

The format is following:

``` json
"petetnt.brackets-name-a-project.namedProjects": {
        "C:/Users/Pete/AppData/Roaming/Brackets/extensions/user/petetnt.brackets-name-a-project/": {
            "_parentPath": "C:/Users/Pete/AppData/Roaming/Brackets/extensions/user/petetnt.brackets-name-a-project/",
            "_name": "petetnt.brackets-name-a-project",
            "name": "Name A Project Extension",
            "bgColor": "blue"
        }
}
```

I could add another pref so you could force the extension to save the preferences to `.brackets.json` by default by [setting the scope to user](https://github.com/adobe/brackets/wiki/Preferences-System#setting-prefs) if that's beneficial, not sure what happens if the file isn't there though so that needs investigating.

**Comment by mihawk90** [comment]
Ah right I could have had that idea myself...

I just copied it into the project file and deleted it from the global, worked perfectly fine :D 

A default option would be nice though :) make it a checkbox/radio button/confirmation to choose from, so it could be chosen on a project by project basis.

/edit
The only thing about just copying the block into the project file is that there's still the absolute path in it, so it's not as portable as it could be

**Comment by petetnt** [comment]
Added this functionality in v0.0.4, thanks for your contribution :+1:

**Comment by mihawk90** [comment]
It still stores the full path though :( it makes it hard to be portable unfortunately. I see that the path is also used as the main object property name or however you'd call it, but can't that be left out in the project settings?

I don't know how the code exactly works but is the path necessary?

Wouldn't something like this suffice?

``` JSON
"petetnt.brackets-name-a-project.namedProjects": {
    "_name": "petetnt.brackets-name-a-project",
    "name": "Name A Project Extension",
    "bgColor": "blue"
}
```

**Comment by petetnt** [comment]
Oh right, you are correct about the path not needed for the project level one. It's required for the recent projects list and the user global one though. I'll file another issue and try to fix that later today!

**Comment by mihawk90** [comment]
Awesome! Thank you :)
