### ISSUE TITLE
Default color

### ISSUE THREAD

**Issue by kaiquegarcia** [petetnt/brackets-name-a-project#9]
I don't know if you already solved it, but there's a tiny bug. When we launch the "project name" window to a new project the default font color is "**#0000**" (4 zeros) and there's no effect as color. You can put 3 or 6, but not 4.

_Improvement sugestion_: I liked a lot this extension just because we can change background color and font-color and on this way we can improve our project management. So there's some ideas:
- attatch a **_colorpicker**_ (I think you're doing this now)
- an easy way to change the default settings. Must developers would like it.
- create **_Project Category**_ as default _color schemes_: just changing the category we could change background and font colors without mistakes. For example, we could have two categories ("Working" and "Finished"). Working would have background-color "red" and color "white" and Finished "white" and "black".

And that's it.
Cheers.

**Comment by petetnt** [comment]
Hey @kaiqueg, thanks for your feedback! 

I pushed in a new version `0.0.6` which fixes the default color issue: Brackets replaced {0} with #0000 instead of #000, it had been bothering me for a while now but I kept forgetting about it! :+1: 

Your suggestions are great too! Especially the color picker one should have been there from `0.0.1` but I couldn't get the build in one integrated properly in time so that was put to backlog. I'll look in to those improvements ASAP!
